### ISSUE TITLE
Templates update on pharmaverseadam

### ISSUE THREAD

**Issue by dgrassellyb** [pharmaverse/admiralci#159]
We are having some issues trying to push changes to pharmaverseadam (case if the branch already exists)

we should add a check before this step on check templates : 

```
- name: Checkout repo (PR) 🛎
        if: inputs.push-templates-data
        uses: actions/checkout@v3
        with:
          ref: main
          repository: "${{ github.repository_owner }}/${{ env.repo }}"
          fetch-depth: 2
          token: ${{ secrets.PHARMAVERSE_BOT }}
```

this check would look at pharmaverseadam existing branches, and create output variable target_branch 
(target_branch would be then main or ref: main or update_templates_data branch)
